# ===========================================
# A recipe to deliver static pages via nginx.
#
# @author Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2021-10-01)
# ===========================================

# ===========================================
# MIT License
#
# Copyright (c) 2021 Björn Hempel <bjoern@hempel.li>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ===========================================

# ===========================================
#
# Start app:
# ----------
# ❯ docker-compose up -d
# ❯ open http://localhost:8000
#
# Show logs:
# ----------
# ❯ docker-compose logs -f
#
# Show container:
# ---------------
# ❯ docker container ls
#
# Login into container:
# ---------------------
# ❯ docker-compose exec nginx bash
#
# Restart, stop and start container:
# ----------------------------------
# ❯ docker-compose restart
# ❯ docker-compose stop
# ❯ docker-compose start
#
# Shutdown container:
# -------------------
# ❯ docker-compose down
#
# ===========================================

version: "3.8"

# configure services
services:

  # Nginx to serve the app.
  nginx:
    # @see: https://hub.docker.com/_/nginx
    image: "nginx:latest"
    container_name: "${NAMESPACE_DEVELOPMENT}.nginx"
    hostname: "${NAMESPACE_HOSTNAME_DEVELOPMENT}-nginx"
    restart: always
    ports:
      - ${PORT_NGINX}:80
    volumes:
      # Server static pages
      - ./html:/var/www/web
      # Add nginx configuration
      - ./docker/nginx/conf.d/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network-internal

# configure networks
networks:
  network-internal:
    external: false
    name: "${NAMESPACE_DEVELOPMENT}.network.internal"
